// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEqdxj_29Pqs7FGtmeN7DgxiU0j4IvCig',
    appId: '1:688911596293:web:77892d0ba72eb7195f556c',
    messagingSenderId: '688911596293',
    projectId: 'fireguard-87f0a',
    authDomain: 'fireguard-87f0a.firebaseapp.com',
    storageBucket: 'fireguard-87f0a.firebasestorage.app',
    measurementId: 'G-5F42E4549W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC47oVbfmmyl85QlNGCFLTicThIExPNTUo',
    appId: '1:688911596293:android:01d1a2115f0f90825f556c',
    messagingSenderId: '688911596293',
    projectId: 'fireguard-87f0a',
    storageBucket: 'fireguard-87f0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCV3H_gAJaKnowdKQSk8_4jggWQlG-GUg',
    appId: '1:688911596293:ios:db9b8de54b077b7e5f556c',
    messagingSenderId: '688911596293',
    projectId: 'fireguard-87f0a',
    storageBucket: 'fireguard-87f0a.firebasestorage.app',
    iosClientId: '688911596293-e6ptjdlcjedrs29orcq6ic2npguugdbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCV3H_gAJaKnowdKQSk8_4jggWQlG-GUg',
    appId: '1:688911596293:ios:db9b8de54b077b7e5f556c',
    messagingSenderId: '688911596293',
    projectId: 'fireguard-87f0a',
    storageBucket: 'fireguard-87f0a.firebasestorage.app',
    iosClientId: '688911596293-e6ptjdlcjedrs29orcq6ic2npguugdbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEqdxj_29Pqs7FGtmeN7DgxiU0j4IvCig',
    appId: '1:688911596293:web:b3fdaea056867d5d5f556c',
    messagingSenderId: '688911596293',
    projectId: 'fireguard-87f0a',
    authDomain: 'fireguard-87f0a.firebaseapp.com',
    storageBucket: 'fireguard-87f0a.firebasestorage.app',
    measurementId: 'G-RE5ZRTMBLF',
  );
}
